pull:
	docker pull nginx:1.9.0
	docker pull php:5.6-fpm
	docker pull mysql:5.6
	docker pull redis:3.0
	docker pull memcached:1.4
	docker pull node:0.12

dl:
	wget https://github.com/phalcon/cphalcon/archive/1.3.5.tar.gz -O php/cphalcon.tgz
	wget https://pecl.php.net/get/gearman-1.1.2.tgz -O php/gearman.tgz
	wget https://pecl.php.net/get/redis-2.2.7.tgz -O php/redis.tgz
	wget https://pecl.php.net/get/memcached-2.2.0.tgz -O php/memcached.tgz
	wget https://pecl.php.net/get/xdebug-2.3.2.tgz -O php/xdebug.tgz
	wget https://pecl.php.net/get/msgpack-0.5.6.tgz -O php/msgpack.tgz
	wget https://pecl.php.net/get/memcache-2.2.7.tgz -O php/memcache.tgz
	wget https://pecl.php.net/get/xhprof-0.9.4.tgz -O php/xhprof.tgz
	wget https://getcomposer.org/composer.phar -O php/composer.phar

build:
	make build-nginx
	make build-mysql
	make build-php
	make build-node

build-nginx:
	docker build -t simiam/nginx ./nginx

run-nginx:
	docker run -i -d --name=nginx -h nginx -p 80:80 -v /home/simiam/opt:/opt --link php:php -t simiam/nginx

in-nginx:
	docker run -i --name=nginx -h nginx -p 80:80 -v /home/simiam/opt:/opt --link php:php -t simiam/nginx /bin/bash

build-php:
	docker build -t simiam/php ./php

run-php:
	docker run -i -d --name=php -h php -p 9000:9000 -v /home/simiam/opt:/opt --link mysql:mysql -t simiam/php

in-php:
	docker run -i --name=php -h php -p 9000:9000 -v /home/simiam/opt:/opt --link mysql:mysql -t simiam/php /bin/bash

build-mysql:
	docker build -t simiam/mysql ./mysql

run-mysql:
	docker run -i -d --name=mysql -h mysql -p 3306:3306 -v /home/simiam/opt/data/mysql:/var/lib/mysql -e MYSQL_ROOT_PASSWORD=***** -t simiam/mysql

in-mysql:
	docker run -i --name=mysql -h mysql -p 3306:3306  -v /home/simiam/opt/data/mysql:/var/lib/mysql -e MYSQL_ROOT_PASSWORD=***** -t simiam/mysql /bin/bash

build-node:
	docker build -t simiam/node ./node

run-node:
	docker run -i -d --name=node -h node -p 8001:8001 -v /home/simiam/opt:/opt -t simiam/node

in-node:
	docker run -i --name=node -h node -p 8001:8001 -v /home/simiam/opt:/opt -t simiam/node /bin/bash

build-elasticsearch:
	docker build -t simiam/elasticsearch ./elasticsearch

run-elasticsearch:
	docker run -i -d --name=elasticsearch -h elasticsearch -p 9200:9200 -p 9300:9300 -v /home/simiam/opt/data/elasticsearch:/usr/share/elasticsearch/data -t simiam/elasticsearch

in-elasticsearch:
	docker run -i -p 9200:9200 -p 9300:9300 -v /home/simiam/opt/data/elasticsearch:/usr/share/elasticsearch/data -t simiam/elasticsearch /bin/bash

build-gearman:
	docker build -t simiam/gearman ./gearman

run-gearman:
	docker run -d --name=gearman -h gearman -p 4730:4730 -v /home/simiam/opt:/opt -it simiam/gearman

clean:
	docker rmi -f $(shell docker images -a | grep "<none>" | awk "{print \$3}")
